# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [337]:
import pandas as pd

# Dataset 1: Product details
df1=pd.DataFrame({
    "ProductID":[101,102,103],
    "ProductName":["Pen","Notebook","Marker"],
    "Price":[10,50,30]
})

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2=pd.DataFrame({
     "ProductID":[104,105],
     "ProductName":["Pencil","Eraser"],
     "Price":[5,8]
 })
# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3=pd.DataFrame({
     "Stock":[100,60,80],
     "Rating":[4.5,4.7,4.8]
 })

In [338]:
df1

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30

In [339]:
df2

   ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser      8

In [340]:
pd.concat([df1,df2],ignore_index=True)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [341]:
pd.concat((df1,df2),axis=0)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [342]:
pd.concat([df1,df3],axis=0) #row increase

   ProductID ProductName  Price  Stock  Rating
0      101.0         Pen   10.0    NaN     NaN
1      102.0    Notebook   50.0    NaN     NaN
2      103.0      Marker   30.0    NaN     NaN
0        NaN         NaN    NaN  100.0     4.5
1        NaN         NaN    NaN   60.0     4.7
2        NaN         NaN    NaN   80.0     4.8

In [343]:
pd.concat([df1,df3],axis=1) #columns increase

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [344]:
products = pd.concat([df1, df2], ignore_index=True)
# ignore_index=True is recommended to avoid duplicate index 0, 1

In [345]:
sales = pd.DataFrame({
    "ProductID": [101, 102, 104, 106],
    "UnitsSold": [500, 200, 150, 50]
})

In [346]:
pd.merge(products,sales)

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [347]:
pd.merge(products,sales,on="ProductID",how="inner") #how inner join and on ProductID  #both common

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [348]:
pd.merge(products,sales,on="ProductID",how="left")  #only focused on products i.e left

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      8        NaN

In [349]:
pd.merge(products,sales,on="ProductID",how="right") #focused on right

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50

In [350]:
pd.merge(products,sales,on="ProductID",how="outer" )   #all will come  both 105 and 106 will also come

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [351]:
products = pd.concat([df1, df2], ignore_index=True)
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [352]:
stock=pd.DataFrame({
    "Stock":[100,60,80,120,150 ]
},index=[101,102,103,104,105])
stock

     Stock
101    100
102     60
103     80
104    120
105    150

In [353]:
p_dataset=products.set_index('ProductID')
p_dataset

          ProductName  Price
ProductID
101               Pen     10
102          Notebook     50
103            Marker     30
104            Pencil      5
105            Eraser      8

In [354]:
p_dataset.join(stock) # when same index come in picture

          ProductName  Price  Stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [355]:
import pandas as pd

# Sales data
sales = pd.DataFrame({
    "ProductID": [201, 202, 203, 204],
    "UnitsSold": [500, 300, 400, 250]
})

# Revenue data (missing ProductID 204, extra 205)
revenue = pd.DataFrame({
    "ProductID": [201, 202, 203, 205],
    "Revenue": [7500, 4500, 6800, 1200]
})
print("Sales Data:")
print(sales)
print("\nRevenue Data:")
print(revenue)

Sales Data:
   ProductID  UnitsSold
0        201        500
1        202        300
2        203        400
3        204        250

Revenue Data:
   ProductID  Revenue
0        201     7500
1        202     4500
2        203     6800
3        205     1200

In [356]:
merged_df=pd.merge(sales,revenue ,on="ProductID",how="outer") #some null value will also come becuase there are  join on outer
merged_df

   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0

In [357]:
merged_df=pd.merge(sales,revenue ,on="ProductID",how="inner")
merged_df

   ProductID  UnitsSold  Revenue
0        201        500     7500
1        202        300     4500
2        203        400     6800

In [358]:
merged_df=pd.merge(sales,revenue ,on="ProductID",how="left")
merged_df

   ProductID  UnitsSold  Revenue
0        201        500   7500.0
1        202        300   4500.0
2        203        400   6800.0
3        204        250      NaN

In [359]:
merged_df=pd.merge(sales,revenue ,on="ProductID",how="right")
merged_df

   ProductID  UnitsSold  Revenue
0        201      500.0     7500
1        202      300.0     4500
2        203      400.0     6800
3        205        NaN     1200

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [360]:

# 1. Create three DataFrames: Products, Sales, and Revenue
import pandas as pd

# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})

sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})

revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})
print("Products DataFrame:")
print(products)
print("\nSales DataFrame:")
print(sales)
print("\nRevenue DataFrame:")
print(revenue)

Products DataFrame:
   ProductID ProductName
0        101         Pen
1        102    Notebook
2        103      Pencil
3        104      Eraser

Sales DataFrame:
   ProductID  UnitsSold
0        101        200
1        102        150
2        103        300
3        105         50

Revenue DataFrame:
   ProductID  Revenue
0        101     1000
1        102     2500
2        104      800
3        105      200

In [364]:

# 1. Create three DataFrames: Products, Sales, and Revenue
import pandas as pd

# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})

sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})

revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})
print("Products DataFrame:")
print(products)
print("\nSales DataFrame:")
print(sales)
print("\nRevenue DataFrame:")
print(revenue)
# 2. Concatenate them vertically and horizontally
pd.concat([products,sales,revenue],axis=0,ignore_index=True)
# Write your code here
pd.concat([products,sales,revenue],axis=1)
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
pd.merge(sales,revenue,on='ProductID',how='inner')
# 4. Join Products with Sales based on index or a key
# Write your code here
# Set ProductID as index first
products_idx = products.set_index("ProductID") #join index bana leta hai aur kaam karta hai
sales_idx = sales.set_index("ProductID")
# Now join works because it aligns the indices
result = products_idx.join(sales_idx, how="inner")
result
# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

Products DataFrame:
   ProductID ProductName
0        101         Pen
1        102    Notebook
2        103      Pencil
3        104      Eraser

Sales DataFrame:
   ProductID  UnitsSold
0        101        200
1        102        150
2        103        300
3        105         50

Revenue DataFrame:
   ProductID  Revenue
0        101     1000
1        102     2500
2        104      800
3        105      200

          ProductName  UnitsSold
ProductID
101               Pen        200
102          Notebook        150
103            Pencil        300

In [365]:
joined = products.merge(sales, on="ProductID", how="left")
print("\nProducts joined with Sales (left join):")
print(joined)

# 5. Analyze missing values after joins
print("\nMissing values summary (Products + Sales):")
print(joined.isna().sum())

print("\nInfo about joined DataFrame:")
print(joined.info())

print("\nDescribe numeric columns (joined DataFrame):")
print(joined.describe())

Products joined with Sales (left join):
   ProductID ProductName  UnitsSold
0        101         Pen      200.0
1        102    Notebook      150.0
2        103      Pencil      300.0
3        104      Eraser        NaN

Missing values summary (Products + Sales):
ProductID      0
ProductName    0
UnitsSold      1
dtype: int64

Info about joined DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    4 non-null      int64
 1   ProductName  4 non-null      object
 2   UnitsSold    3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None

Describe numeric columns (joined DataFrame):
        ProductID   UnitsSold
count    4.000000    3.000000
mean   102.500000  216.666667
std      1.290994   76.376262
min    101.000000  150.000000
25%    101.750000  175.000000
50%    102.500000  200.000000
75%    103.250000  250.000000
max    104.000000  300.000000

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.