# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [146]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)

In [147]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [148]:
b.isna() #or b.isnull() #jahan jahan nahi hai value vahan true aayega

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [149]:
b.isna().sum() #kis row mein kitna missing value hai

Name     0
Age      2
City     1
Score    1
dtype: int64

In [150]:
b.dropna() #only those row is here which is not null , other dropped , # and inplace=true nahi kara hai toh really mein original change nahi hua hai

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [151]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [152]:
b['Age']=b['Age'].fillna(b['Age'].mean())
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000       None    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [153]:
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000       None    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [154]:
b['City']=b['City'].fillna(b['City'].mode())
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [155]:
b['Score']=b['Score'].fillna(0) #filled with 0
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [156]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [157]:
b['Score']=b['Score'].astype(float) #float , int ,str ,bool
b

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [158]:
c=b.copy()
c

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [159]:
c['Name']=c['Name'].replace("Bob","Robert")
c

      Name  Age  Score
0    Alice   25   88.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [160]:
c['Score']=c['Score'].replace({85.0:86.9,0.0:7.2})
c

      Name  Age  Score
0    Alice   25   88.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   86.9
4     Emma   22   95.0

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [161]:
c

      Name  Age  Score
0    Alice   25   88.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   86.9
4     Emma   22   95.0

In [162]:
c.drop(['Name','Score'],axis=1) #shallow copy

   Age
0   25
1   30
2   35
3   40
4   22

In [163]:
c.drop([0,2])

     Name  Age  Score
1  Robert   30   92.0
3   David   40   86.9
4    Emma   22   95.0

In [164]:
c.drop(['Age'],axis=1,inplace=True)
c

      Name  Score
0    Alice   88.0
1   Robert   92.0
2  Charlie   79.0
3    David   86.9
4     Emma   95.0

In [165]:
data = { "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
        "Age": [25, 30, 35, 25, 30, 40],
         "Score": [88, 92, 79, 88, 92, 85] }

df = pd.DataFrame(data)

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [166]:
data = { "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
        "Age": [25, 30, 35, 25, 30, 40],
         "Score": [88, 92, 79, 88, 92, 85] }

df = pd.DataFrame(data)

In [167]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [168]:
df.drop_duplicates() #duplicate dropped

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

In [169]:
df.drop_duplicates(inplace=True)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [170]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data1 = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

x = pd.DataFrame(data1)

print("Original messy DataFrame:")
print(x)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.

In [171]:
x

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [172]:
x.isnull()

    Name    Age   City  Score  Extra
0  False  False  False  False  False
1  False  False  False   True  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5   True  False  False  False  False

In [173]:
x.dropna()

    Name Age       City  Score Extra
0  Alice  25      Delhi   85.0     x
3  David  40  Bangalore   88.0     x
4  Alice  25      Delhi   85.0     y

In [174]:
x

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [175]:
x['Age']=x['Age'].fillna("97")
x

     Name Age       City  Score Extra
0   Alice  25      Delhi   85.0     x
1     Bob  30     Mumbai    NaN     y
2  Chrlie  97        Pun   78.0     z
3   David  40  Bangalore   88.0     x
4   Alice  25      Delhi   85.0     y
5    None  30     Mumbai   91.0     z

In [176]:
x['Age']=x['Age'].astype(int)
x

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai    NaN     y
2  Chrlie   97        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5    None   30     Mumbai   91.0     z

In [177]:
x['City']=x['City'].replace("Pun","Pune")
x

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai    NaN     y
2  Chrlie   97       Pune   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5    None   30     Mumbai   91.0     z

In [178]:
x.drop('Extra',axis=1,inplace=True)
x

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai    NaN
2  Chrlie   97       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0

In [180]:
x.drop_duplicates()

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai    NaN
2  Chrlie   97       Pune   78.0
3   David   40  Bangalore   88.0
5    None   30     Mumbai   91.0

In [182]:
x.info()
x

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai    NaN
2  Chrlie   97       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0

In [184]:
# x.drop_duplicates(axis=1) # so we have not currently any coluns duplicate so we have to not apply it
x

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai    NaN
2  Chrlie   97       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5    None   30     Mumbai   91.0