# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [67]:
import pandas as pd
import numpy as np
a={
    "Name":["Alice","Bob","Charlie","David","Emma"],
    "Age":[25,30,35,40,22],
    "Score":[88,92,79,85,95]
}
df=pd.DataFrame(a)

In [68]:
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [69]:
df['Age']>30

0    False
1    False
2     True
3     True
4    False
Name: Age, dtype: bool

In [70]:
df[df['Age']>30]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [71]:
#Multiple conditions
df[(df['Age']>25) & (df['Score']>85)]

  Name  Age  Score
1  Bob   30     92

In [72]:
df[(df['Age']<25) |  (df['Score']>90)]

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

In [73]:
df[~(df['Score']>85)] #not condition

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [74]:
# we have done above

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [75]:
df.query("Age>25")

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85

In [76]:
df.query("Age>25 and Score>=85") #here and is same as python

    Name  Age  Score
1    Bob   30     92
3  David   40     85

In [77]:
hold=90 # a variable
df.query("Score > @hold")

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [78]:
df['Name'].str.lower() #shadow copy

0      alice
1        bob
2    charlie
3      david
4       emma
Name: Name, dtype: object

In [79]:
# df['Name']=df['Name'].str.lower() #actual dataset will be changed
# df['Name']=df['Name'].str.upper()

In [80]:
df['Name'].str.contains('a',case=False) #case false means ignore capital a or small a

0     True
1    False
2     True
3     True
4     True
Name: Name, dtype: bool

In [81]:
df['Name'].str.replace("Charlie","Charles")

0      Alice
1        Bob
2    Charles
3      David
4       Emma
Name: Name, dtype: object

In [84]:
df[df['Name'].str.startswith('A')]

    Name  Age  Score
0  Alice   25     88

In [85]:
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [83]:


# 1. Build a DataFrame with columns: Name, Age, City, Score

# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

In [86]:
import pandas as pd
data1={
    "Name":["Alice","Bob","Charlie","David","Emma","Frank"],
    "Age":[24,32,28,40,22,30],
    "City":["Delhi","Mumbai","Pune","Chennai","Delhi","Mumbai"],
    "Score":[90,82,88,75,95,84]
}
x=pd.DataFrame(data1)

In [88]:
x["Age"]>25 #boolean indexing

0    False
1     True
2     True
3     True
4    False
5     True
Name: Age, dtype: bool

In [89]:
x[x["Age"]>25]

      Name  Age     City  Score
1      Bob   32   Mumbai     82
2  Charlie   28     Pune     88
3    David   40  Chennai     75
5    Frank   30   Mumbai     84

In [92]:
x[(x["City"] =="Delhi") | (x["City"]=="Mumbai")]

    Name  Age    City  Score
0  Alice   24   Delhi     90
1    Bob   32  Mumbai     82
4   Emma   22   Delhi     95
5  Frank   30  Mumbai     84

In [100]:
x.query("Age<35 and Score>85")

      Name  Age   City  Score
0    Alice   24  Delhi     90
2  Charlie   28   Pune     88
4     Emma   22  Delhi     95

In [104]:
x['City']=x['City'].str.lower()
x

      Name  Age     City  Score
0    Alice   24    delhi     90
1      Bob   32   mumbai     82
2  Charlie   28     pune     88
3    David   40  chennai     75
4     Emma   22    delhi     95
5    Frank   30   mumbai     84

In [105]:
x['City'].str.replace("delhi","new delhi")

0    new delhi
1       mumbai
2         pune
3      chennai
4    new delhi
5       mumbai
Name: City, dtype: object

In [108]:
x['City']=x['City'].str.replace("delhi","new delhi")
x

      Name  Age           City  Score
0    Alice   24  new new delhi     90
1      Bob   32         mumbai     82
2  Charlie   28           pune     88
3    David   40        chennai     75
4     Emma   22  new new delhi     95
5    Frank   30         mumbai     84

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.