# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [56]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

In [57]:
df.dtypes

OrderID       int64
OrderDate    object
Customer     object
Amount        int64
dtype: object

In [58]:
#so to convert a column into date , there should be one type
df['OrderDate']=pd.to_datetime(df['OrderDate'],errors="coerce") #so different date hai toh kisi ek ko pakad ke convert kar dega us type baki ko NAT , so ek type hi rahna chahiye date ka in data

In [59]:
df.set_index('OrderDate')

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
NaT            1002      Bob     400
NaT            1003  Charlie     150
2024-01-20     1004    David     300
NaT            1005     Emma     500

In [60]:
df_idx=df.set_index('OrderDate') #it is an another dataframe df_idx
df #here df_setindex actually original pe apply nahi hua hai

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002        NaT      Bob     400
2     1003        NaT  Charlie     150
3     1004 2024-01-20    David     300
4     1005        NaT     Emma     500

In [61]:
df_idx

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
NaT            1002      Bob     400
NaT            1003  Charlie     150
2024-01-20     1004    David     300
NaT            1005     Emma     500

In [62]:
df_idx.resample("M")["Amount"].sum() #month , year and date ke basis pe ham nikal saktre hain

/tmp/ipykernel_2159/3149036043.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_idx.resample("M")["Amount"].sum() #month , year and date ke basis pe ham nikal saktre hain

OrderDate
2024-01-31    550
Name: Amount, dtype: int64

In [63]:
df_idx.resample("Y")["Amount"].sum()

/tmp/ipykernel_2159/211439033.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df_idx.resample("Y")["Amount"].sum()

OrderDate
2024-12-31    550
Name: Amount, dtype: int64

In [64]:
df_idx.resample("D")["Amount"].sum()

OrderDate
2024-01-05    250
2024-01-06      0
2024-01-07      0
2024-01-08      0
2024-01-09      0
2024-01-10      0
2024-01-11      0
2024-01-12      0
2024-01-13      0
2024-01-14      0
2024-01-15      0
2024-01-16      0
2024-01-17      0
2024-01-18      0
2024-01-19      0
2024-01-20    300
Name: Amount, dtype: int64

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [65]:
#done above

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [66]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)
data = {
    "VisitDate": [
        "2024-01-03", "2024/01/08", "15-01-2024", "2024-02-02",
        "2024-02-15", "2024/03/01", "2024-03-12", "01-04-2024"
    ],
    "Visitors": [120, 150, 90, 200, 180, 220, 210, 300]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# 2️⃣ Convert VisitDate to datetime
df["VisitDate"]=pd.to_datetime(df['VisitDate'],errors="coerce")
# Write your code here

# 3️⃣ Set VisitDate as the index
# Write your code here
df.set_index('VisitDate')
# 4️⃣ Resample to get total visitors per month
# Write your code here
df_idx=df.set_index('VisitDate')
df_idx
df_idx.resample('M')["Visitors"].sum()
# 5️⃣ Resample to get average visitors per week
df_idx.resample('W')["Visitors"].mean()
# Write your code here

Original DataFrame:
    VisitDate  Visitors
0  2024-01-03       120
1  2024/01/08       150
2  15-01-2024        90
3  2024-02-02       200
4  2024-02-15       180
5  2024/03/01       220
6  2024-03-12       210
7  01-04-2024       300

/tmp/ipykernel_2159/1980111250.py:23: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_idx.resample('M')["Visitors"].sum()

VisitDate
2024-01-07    120.0
2024-01-14      NaN
2024-01-21      NaN
2024-01-28      NaN
2024-02-04    200.0
2024-02-11      NaN
2024-02-18    180.0
2024-02-25      NaN
2024-03-03      NaN
2024-03-10      NaN
2024-03-17    210.0
Name: Visitors, dtype: float64

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.