# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [131]:
import pandas as pd
data={
    "Employee":["John0","Sarah","Mike","Anna","Tom","Laura","Steve","Kate"],
    "Department":["HR","IT","IT","Finance","Finance","HR","IT","Finance"],
    "Salary":[50000,70000,72000,65000,60000,52000,75000,58000],
    "Age":[28,32,30,27,35,29,31,26]
}
df=pd.DataFrame(data)
df

  Employee Department  Salary  Age
0    John0         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [132]:
df['Department'].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [133]:
df[df['Department']=="IT"]

  Employee Department  Salary  Age
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
6    Steve         IT   75000   31

In [134]:
df[df['Department']=="IT"]['Salary'].mean() #IT DEPARTMENT SALARY

np.float64(72333.33333333333)

In [135]:
df.groupby('Department')['Salary'].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [136]:
df.groupby('Department')['Salary'].agg(['mean','max','min']) #agg is aggregation

                    mean    max    min
Department
Finance     61000.000000  65000  58000
HR          51000.000000  52000  50000
IT          72333.333333  75000  70000

In [137]:
df.groupby('Department')['Employee'].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [138]:
df.groupby('Department').agg(
    {
        "Salary":["mean","median","max","min"],
        "Age":["mean","max"]
    }
)

                  Salary                               Age
                    mean   median    max    min       mean max
Department
Finance     61000.000000  60000.0  65000  58000  29.333333  35
HR          51000.000000  51000.0  52000  50000  28.500000  29
IT          72333.333333  72000.0  75000  70000  31.000000  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [139]:
#in chi square table contigency table
df.pivot_table(values="Salary",index='Department')

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [140]:
df.pivot_table(values="Salary",index='Department',aggfunc="mean")

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [141]:
df.pivot_table(values=["Salary","Age"],index='Department',aggfunc="mean")

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [142]:
import seaborn as sns
v=sns.load_dataset('flights') #automatic data set which is made for use
v

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [143]:
v['year'].value_counts()

year
1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: count, dtype: int64

In [144]:
v.pivot_table(values='passengers',index='year',columns='month') #all passengers

/tmp/ipykernel_393/3515286256.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  v.pivot_table(values='passengers',index='year',columns='month') #all passengers

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [145]:
v.pivot_table(values='passengers',index='year',columns='month',aggfunc=["max","mean"]) #all passengers

/tmp/ipykernel_393/1874903720.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  v.pivot_table(values='passengers',index='year',columns='month',aggfunc=["max","mean"]) #all passengers
/tmp/ipykernel_393/1874903720.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  v.pivot_table(values='passengers',index='year',columns='month',aggfunc=["max","mean"]) #all passengers

       max                                               ...   mean         \
month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  ...    Mar    Apr
year                                                     ...
1949   112  118  132  129  121  135  148  148  136  119  ...  132.0  129.0
1950   115  126  141  135  125  149  170  170  158  133  ...  141.0  135.0
1951   145  150  178  163  172  178  199  199  184  162  ...  178.0  163.0
1952   171  180  193  181  183  218  230  242  209  191  ...  193.0  181.0
1953   196  196  236  235  229  243  264  272  237  211  ...  236.0  235.0
1954   204  188  235  227  234  264  302  293  259  229  ...  235.0  227.0
1955   242  233  267  269  270  315  364  347  312  274  ...  267.0  269.0
1956   284  277  317  313  318  374  413  405  355  306  ...  317.0  313.0
1957   315  301  356  348  355  422  465  467  404  347  ...  356.0  348.0
1958   340  318  362  348  363  435  491  505  404  359  ...  362.0  348.0
1959   360  342  406  396  420  472  548  559  463  407  ...  406.0  396.0
1960   417  391  419  461  472  535  622  606  508  461  ...  419.0  461.0


month    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec
year
1949   121.0  135.0  148.0  148.0  136.0  119.0  104.0  118.0
1950   125.0  149.0  170.0  170.0  158.0  133.0  114.0  140.0
1951   172.0  178.0  199.0  199.0  184.0  162.0  146.0  166.0
1952   183.0  218.0  230.0  242.0  209.0  191.0  172.0  194.0
1953   229.0  243.0  264.0  272.0  237.0  211.0  180.0  201.0
1954   234.0  264.0  302.0  293.0  259.0  229.0  203.0  229.0
1955   270.0  315.0  364.0  347.0  312.0  274.0  237.0  278.0
1956   318.0  374.0  413.0  405.0  355.0  306.0  271.0  306.0
1957   355.0  422.0  465.0  467.0  404.0  347.0  305.0  336.0
1958   363.0  435.0  491.0  505.0  404.0  359.0  310.0  337.0
1959   420.0  472.0  548.0  559.0  463.0  407.0  362.0  405.0
1960   472.0  535.0  622.0  606.0  508.0  461.0  390.0  432.0

[12 rows x 24 columns]

In [146]:
import pandas as pd
data={
    "Employee":["John0","Sarah","Mike","Anna","Tom","Laura","Steve","Kate"],
    "Department":["HR","IT","IT","Finance","Finance","HR","IT","Finance"],
    "Salary":[50000,70000,72000,65000,60000,52000,75000,58000],
    "Age":[28,32,30,27,35,29,31,26]
}
df1=pd.DataFrame(data)
df1

  Employee Department  Salary  Age
0    John0         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [147]:
df1['AgeGroup']=pd.cut(df1['Age'],bins=[25,30,35,40],labels=['25-30','31-35','36-40'])
df1 #an agegroup section has been created

  Employee Department  Salary  Age AgeGroup
0    John0         HR   50000   28    25-30
1    Sarah         IT   70000   32    31-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [148]:
pd.crosstab(df1['Department'],df1['AgeGroup'])

AgeGroup    25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [150]:
import pandas as pd
# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "George", "Hannah"],
    "Salary": [50000, 65000, 60000, 70000, 52000, 58000, 72000, 51000],
    "Age": [28, 35, 30, 40, 26, 32, 38, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Mumbai", "Delhi"]
}
df=pd.DataFrame(data)
# 2. Group by Department to get average Salary and max Age
df.groupby('Department').agg({"Salary":'mean',"Age":'max'})
# Write your code here

# 3. Apply multiple aggregations using agg()
multi_agg = df.groupby("Department").agg(
    Salary_mean=("Salary", "mean"),
    Salary_min=("Salary", "min"),
    Age_max=("Age", "max"),
    Age_min=("Age", "min"),
    Count=("Employee", "count")
)
print("\nMultiple aggregations by Department:")
print(multi_agg)
# Example: mean Salary, max Age per Department

# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
pivot = df.pivot_table(values="Salary", index="Department", columns="City", aggfunc="mean", fill_value=0)
print("\nPivot table: Mean Salary by Department and City")
print(pivot)
# 5. Build a crosstab for Department vs City
cross = pd.crosstab(df["Department"], df["City"])
print("\nCrosstab: Department vs City")
print(cross)
# Write your code here

Multiple aggregations by Department:
            Salary_mean  Salary_min  Age_max  Age_min  Count
Department
Finance         59000.0       58000       32       30      2
HR              51000.0       50000       28       26      3
IT              69000.0       65000       40       35      3

Pivot table: Mean Salary by Department and City
City        Chennai    Delhi   Mumbai
Department
Finance         0.0  59000.0      0.0
HR              0.0  50500.0  52000.0
IT          70000.0      0.0  68500.0

Crosstab: Department vs City
City        Chennai  Delhi  Mumbai
Department
Finance           0      2       0
HR                0      2       1
IT                1      0       2

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.