# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [23]:
import numpy as np
import pandas as pd
data={
  "Name":["Alice","Bob","Charlie","David","Emma"],
  "Math":[88,75,92,60,85],
  "Science":[90,80,78,70,95]
}
df=pd.DataFrame(data)
df

      Name  Math  Science
0    Alice    88       90
1      Bob    75       80
2  Charlie    92       78
3    David    60       70
4     Emma    85       95

In [24]:
df['ToatalMarks']=df[['Math','Science']].apply(lambda row:row.sum(),axis=1)

In [25]:
df

      Name  Math  Science  ToatalMarks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [26]:
col_meandf=df[['Math','Science']].apply(lambda  col:col.mean()) #here by default axis=0
col_meandf

Math       80.0
Science    82.6
dtype: float64

In [27]:
def to_grade(s):#custom function
   if s>=90:
    return "A"
   elif s>=80:
    return "B"
   elif s>=70:
    return "C"
   else:
    return "D"
df['MathsGrade']=df['Math'].apply(to_grade)
df

      Name  Math  Science  ToatalMarks MathsGrade
0    Alice    88       90          178          B
1      Bob    75       80          155          C
2  Charlie    92       78          170          A
3    David    60       70          130          D
4     Emma    85       95          180          B

In [28]:
df['Name']=df['Name'].map(str.lower)
df

      Name  Math  Science  ToatalMarks MathsGrade
0    alice    88       90          178          B
1      bob    75       80          155          C
2  charlie    92       78          170          A
3    david    60       70          130          D
4     emma    85       95          180          B

In [29]:
df['Math']=df['Math'].map(lambda x:x+5)
df

      Name  Math  Science  ToatalMarks MathsGrade
0    alice    93       90          178          B
1      bob    80       80          155          C
2  charlie    97       78          170          A
3    david    65       70          130          D
4     emma    90       95          180          B