# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [471]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b.head(2)

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

In [472]:
b.head() #by defdault give 5 row

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [473]:
b.head(3) #first 3 rows

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

In [474]:
b.tail(3) #last three rows

      Name  Age  Score
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [475]:
b.info() #non null means , value is not null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [476]:
b.shape #5 rows and 3 columns

(5, 3)

In [477]:
print(b) #here jaisa value hai vaisa hi hai data types , in numpy agar ek chiz dusra rahta tha toh sari ki sari chiz object ho jati thi like if a element is tring whole array ka data type object ho jata tha

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [478]:
b.dtypes #harek columns ka datatypes

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [479]:
print(b)
b['Name'] ##now here we will select here jo chiz pahle select karenge vo column honge becuase dabdaba jayda rahta hai in some cases  like here

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

In [480]:
b[['Name','Age']] #fancy indexing

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

In [481]:
b.loc[0] #row number 0 ka aaya and series ban gaya

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

In [482]:
b.loc[0,"Score"] #0 index pe Score ka value aa gaya hai  which is 88

np.int64(88)

In [483]:
print(b)
b.loc[1:3,["Name","Age"]]  #1 se 3 including , slicing , columns name #note that 1:3 means 1 se 3 location le raha hai ye but iloc thoda sa different kaam karta hai

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name  Age
1      Bob   30
2  Charlie   35
3    David   40

In [484]:
b.iloc[0] #same thing aaya but iloc is used when rows like other hai jaise 1,2,3,4,5 jaise ho toh iloc index locate karta hai like 0 for 1 1 for 2 like that but yahan 0 se hi chalu hai toh no problem

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [485]:
b.index

RangeIndex(start=0, stop=5, step=1)

In [486]:
b.columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [487]:
b.values #convert all values row wise into numpy array

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [488]:

# c=b.rename(columns={"Score":"Marks"}) #we have not changed our original dataset that's why we kept in c
# print(c)

In [489]:
#inplace true means copy pe na lagke pure dat ape hi apply ho jaye
b.rename(columns={"Score":"Marks"}) #here copy only without inplace=True , and it will apply only on copy , our main original will not change
b #but still score so inplace when true then it will apply on original data

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [490]:
b.rename(columns={"Score":"Marks"},inplace=True) #ye karne par hamara original dataset change ho jayenge from score to marks , # it will apply on main data
b

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [491]:
b.rename(columns={"Marks":"Score"},inplace=True) #again changed original
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

c=b.set_index("Name") #and Name as index points
c # and name came as a index
c.loc["Alice"] #and we got alice data as a series

In [492]:
b.set_index("Name",inplace=True) #so mera b ko bigad diya , matlab original dataset ko change kar diya , aur agar hamein ise dubara original mein lana hai toh we will use reset
b

         Age  Score
Name
Alice     25     88
Bob       30     92
Charlie   35     79
David     40     85
Emma      22     95

In [493]:
b.reset_index(inplace=True)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [494]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).

In [495]:
x=pd.DataFrame(data)
x.head(3)

      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78

In [496]:
x.tail(2)

    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95

In [497]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [498]:
x

      Name  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [499]:
x.index

RangeIndex(start=0, stop=5, step=1)

In [500]:
x.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='object')

In [501]:
x[["Name","Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

In [502]:
x.rename(columns={"Score":"Marks"},inplace=True)
x

      Name  Age       City  Marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [503]:
x.set_index("Name")

         Age       City  Marks
Name
Alice     25      Delhi     85
Bob       30     Mumbai     91
Charlie   35       Pune     78
David     40  Bangalore     88
Emma      22    Chennai     95

In [504]:
x.reset_index(inplace=False)

   index     Name  Age       City  Marks
0      0    Alice   25      Delhi     85
1      1      Bob   30     Mumbai     91
2      2  Charlie   35       Pune     78
3      3    David   40  Bangalore     88
4      4     Emma   22    Chennai     95

In [505]:
x

      Name  Age       City  Marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [509]:
df.shape

(5, 4)

In [510]:
df.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='object')

In [511]:
df.dtypes

Name     object
Age       int64
City     object
Score     int64
dtype: object

In [514]:
sb=x[["Name","City"]] #subdataframe with Name and City
sb

      Name       City
0    Alice      Delhi
1      Bob     Mumbai
2  Charlie       Pune
3    David  Bangalore
4     Emma    Chennai