# 🐼 Pandas - Class 1: Introduction & Setup
#we have used numpy becuase there is something array which is fast in comparison of list .. But now
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
generally we use datatable in 2d like a table which contains name , ages , gender and salray for manipulate, use and  exchange in this data table then we use DataFrame..
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

#And note that in Machine learning -> DataFrame is used mostly..

#Note that For Data Analyssis(like mean,median,ode , numbers dekhna hai toh  and if anything is miss then for filling etc )-> we use
  - Numpy and Pandas for data analysis and pandas toh bahut use hote hain

#And Note that For Data Visualisation(like pie charts  , bar graphs etc)-> we use
  - Matplotlib and seaborn library..

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [2]:
import numpy as np
import pandas as pd
#imported both becuase somtimes dono ka use saath saath aa jata hai

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [3]:
a=[10,20,30,40,50]
s=pd.Series(a) # so ek column ban gaya , i.e ek series ban gaya yani can say only one row
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
a=[10,20,30,40,50]
s=pd.Series(a,name="marks")
s

0    10
1    20
2    30
3    40
4    50
Name: marks, dtype: int64

In [15]:
d={"Akarsh":90,"Ghannath":100,"Rohan":60,"Shivam":70,"Ayush":80}
s=pd.Series(d,name="Marks")
s

Akarsh       90
Ghannath    100
Rohan        60
Shivam       70
Ayush        80
Name: Marks, dtype: int64

In [18]:
#WE WILL USE VERY LESS OF SERIES SO WHY WE WILL WASTE OUR TIME ON IT
#WE WILL USE MOST DataFrame so we ill go to that and function similiar hote hain
d={
    "Name":["Alice","Bob","Charlie","David"],
    "Marks":[90,85,78,92],
    "Subject":["Math","Science","History","English"]
}
pd.Series(d) #but kuchh khas nahi lag raha

Name            [Alice, Bob, Charlie, David]
Marks                       [90, 85, 78, 92]
Subject    [Math, Science, History, English]
dtype: object

In [20]:
d={
    "Name":["Alice","Bob","Charlie","David"],
    "Marks":[90,85,78,92],
    "Subject":["Math","Science","History","English"]
}
pd.DataFrame(d) #but now you can see how good it is

      Name  Marks  Subject
0    Alice     90     Math
1      Bob     85  Science
2  Charlie     78  History
3    David     92  English

### Creating DataFrame from NumPy Arrays

In [23]:
a=np.array([[1,2,3],
           [3,4,5],
           [6,7,8]])
df=pd.DataFrame(a)
df
#BUT HAM LOGON KO AISE DATA BANANE KI JARURAT NAHI HOTI , HAMLOGON KE PASS CSV FILES , EXCEL FILES HOTE HAIN AND MANY RESOURCES JAHAN SE HAM DOWNLOAD KAR SAKTE HAIN LIKE KAGGLE ETC
#Kaggle is a popular Google-owned online platform and community for data science and machine learning enthusiasts. It hosts competitions to solve real-world problems, provides a vast repository of datasets, offers a browser-based, no-setup environment for writing code (Notebooks), and serves as a hub for learning and collaboration

   0  1  2
0  1  2  3
1  3  4  5
2  6  7  8

In [24]:
a=np.array([[1,2,3],
           [3,4,5],
           [6,7,8]])
df=pd.DataFrame(a,columns=["A","B","C"])
df

   A  B  C
0  1  2  3
1  3  4  5
2  6  7  8

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.

In [ ]:
#so for learning we will use dummy data aise hi data banake and we will use main data like csv and excel for projects..